// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmttewcdryawjyrylkri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtdHRld2Nkcnlhd2p5cnlsa3JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MTAwMjksImV4cCI6MjA2MDE4NjAyOX0.nEXGHiMYs1PriEzj-KYArwM6nEXimUR_NQamygLt144";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);